global using Microsoft.AspNetCore.Authorization;
global using Data;
global using Data.Exceptions;
global using Data.Helpers;
global using Football_Manager;
global using Football_Manager.Extensions;
global using Data.Teams;
global using Microsoft.AspNetCore.Mvc;
global using Controller = Football_Manager.Base.Controller;
global using Data.Players;
global using Football_Manager.Teams;
global using Data.Coaches;
global using Microsoft.AspNetCore.Identity;
global using OneOf;
